"""Generate BAML `test` blocks from the corpus.

The optimizer's corpus format is not ours. `baml-cli optimize` reads BAML
`test` blocks with `@@assert` out of `baml_src/` — there is no CSV or JSONL
ingestion path — while the harness keeps gold as Python in `corpus.py`.
Something has to bridge them, and this is it.

Without this module `baml-cli optimize` runs against ZERO tests, which is
not an error you get told about: it completes, reports a flat pass rate,
and improves nothing.

    uv run python -m harness.testgen

CRITICAL: assertions use `none`, never `null`.

BAML's Jinja has no `null` literal, so `{{this.tax == null}}` compares
against undefined and is ALWAYS FALSE. During development that silently
made every candidate score 33.3%, and the optimizer burned a full run and
real money chasing a test no output could ever satisfy — without once
signalling that the metric was unsatisfiable. A broken eval is worse than
no eval.
"""

from __future__ import annotations

import textwrap

from harness.config import GENERATED_TESTS_BAML
from harness.corpus import CORPUS, Case

HEADER = """\
// GENERATED BY harness/testgen.py — DO NOT EDIT BY HAND.
//
// Source of truth is harness/corpus.py. Regenerate with:
//     uv run python -m harness.testgen
//
// These exist so `baml-cli optimize` has a corpus; it reads BAML test
// blocks and nothing else. Assertions use `none`, never `null` — BAML's
// Jinja has no `null` literal, so `== null` is always false and silently
// makes every candidate fail.
"""


def render_case(case: Case) -> str:
    gold = case.gold
    document = textwrap.indent(case.document.strip(), " " * 6)

    asserts = [
        f'@@assert(category, {{{{this.category == "{gold.category}"}}}})',
        f"@@assert(total, {{{{this.total == {gold.total}}}}})",
        f"@@assert(line_items, {{{{this.line_items|length == {gold.n_items}}}}})",
    ]
    if gold.tax_is_none:
        asserts.append("@@assert(tax_omitted, {{this.tax == none}})")
    else:
        asserts.append("@@assert(tax_present, {{this.tax != none}})")

    rendered_asserts = "\n".join(f"  {a}" for a in asserts)
    rationale = (
        "\n".join(f"// {line}" for line in textwrap.wrap(case.rationale, 72))
        if case.rationale
        else ""
    )

    return f"""{rationale}
test {case.name} {{
  functions [ExtractExpense]
  args {{
    document #"
{document}
    "#
  }}
{rendered_asserts}
}}
"""


def render(cases: list[Case] | None = None) -> str:
    return HEADER + "\n" + "\n".join(render_case(c) for c in (cases or CORPUS))


def write(cases: list[Case] | None = None) -> int:
    """Write generated_tests.baml. Returns the number of tests written."""
    chosen = cases or CORPUS
    GENERATED_TESTS_BAML.write_text(render(chosen))
    return len(chosen)


if __name__ == "__main__":
    count = write()
    print(f"wrote {count} test blocks to {GENERATED_TESTS_BAML}")
